### ISSUE TITLE
点击视频通话的时候报8010

### ISSUE THREAD

**Issue by FrankHnb** [Tencent-RTC/TUICallKit#125]
trtc_api Calling - CallAction_Cancel cancel failed, code: 8010 desc: inviteID invalid or invitation has been processed
onError: code 8010, msg inviteID invalid or invitation has been processed

**Comment by FrankHnb** [comment]
iOS 最新的版本

**Comment by MinTate** [comment]
Hello，可以参照https://github.com/tencentyun/TUICallKit/issues/120 提供一下sdkappid这些信息吗？
