### ISSUE TITLE
多人音视频房间，进入房间的时候打开摄像头失败

### ISSUE THREAD

**Issue by yrhwhowan** [Tencent-RTC/TUICallKit#127]
![1](https://user-images.githubusercontent.com/12543865/192241885-5d26a665-40a0-483b-b32f-0974229e94a5.png)
相机是正常的，相机权限也给了，但还是提示：OnError [code:-1301|msg:Video: Start camera failed.|stream_type:BigStream]。
这是日志：
[LiteAV_C_20220927.zip](https://github.com/tencentyun/TUICallKit/files/9652935/LiteAV_C_20220927.zip)

**Comment by MinTate** [comment]
好的，我们现在看一下，如果有问题可以随时在QQ群联系我们~

**Comment by MinTate** [comment]
> ![1](https://user-images.githubusercontent.com/12543865/192241885-5d26a665-40a0-483b-b32f-0974229e94a5.png) 相机是正常的，相机权限也给了，但还是提示：OnError [code:-1301|msg:Video: Start camera failed.|stream_type:BigStream]。 这是日志： [LiteAV_C_20220927.zip](https://github.com/tencentyun/TUICallKit/files/9652935/LiteAV_C_20220927.zip)

Hello，您好，这个定制设备我们也没有找到，所以需配合一下，替换成我们加完日志 + 逻辑修改的版本，见附件：
[LiteAVSDK_TRTC-9.9.0.9999.aar.zip](https://github.com/tencentyun/TUICallKit/files/9743088/LiteAVSDK_TRTC-9.9.0.9999.aar.zip)

替换步骤：
1. 在 `Android/app`目录下创建libs目录，将附件的文件解压后，把aar拖放进去；
2.修改文件：Android/tuicallkit/build.gradle 的 `api "com.tencent.liteav:LiteAVSDK_TRTC:10.3.0.11225"` 为  `api "com.tencent.liteav:LiteAVSDK_TRTC:9.9.0.9999@aar"` 
3. 替换完成后，按照复现路径执行一下，看看前置摄像头是否可以打开，记录一下时间点；
4. 提供一下sdkappid、时间点、userid，日志；

**Comment by yrhwhowan** [comment]
替换了这个版本，没问题了。

**Comment by MinTate** [comment]
Hello，确认了一下，我们SDK内部的逻辑是：默认使用Camera 1，因为兼容性更好，如果说Camera 1大概失败，会尝试切换到Camera 2 并记录，但是在切换之前会进行一个条件判断，就是Camera 2能力的支持，如果不是Full的话，就不会去切换，因为会有一些兼容性问题，这里的介绍可以看一下这个文档：https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics，
