### ISSUE TITLE
移动端 公众号（TRTC 添加水印，多次切换前置和后置摄像头以后视频有拉伸变形）

### ISSUE THREAD

**Issue by ranguo** [Tencent-RTC/TUICallKit#149]
let sourceVideoTrack = localStream.getVideoTrack();
let settings = sourceVideoTrack.getSettings();
this.oCanvasExport.width = settings.width;
this.oCanvasExport.height = settings.height;
alert("宽度" + settings.width + "摄像头高度" + settings.height);
操作步骤 默认进来  宽是480 高640 》》》》切换到后置摄像头以后 宽 480，高640,》》》》》切换前置摄像头这时候 宽是 640, 高是480

**Comment by Tencent-Alice** [comment]
您好 看起来是接入的webSDK是么？目前的问题就是多次切换摄像头会导致视频分辨率变化，您这边是接入的含UI的集成方案还是自实现UI集成方案？建议使用demo测试看下能否复现呢
webSDK demo：
https://cloud.tencent.com/document/product/647/32398  技术问题 欢迎交流 Q2562367495 注明来意
