### ISSUE TITLE
uni-app小程序的demo跑通后，小程序端接听和挂断按钮闪一下就消失了

### ISSUE THREAD

**Issue by yangmengmeng-1** [Tencent-RTC/TUICallKit#153]
uni-app小程序的demo跑通后，web端给小程序发起视频通话，小程序端接听和挂断按钮闪一下就消失了。前两次是好使的，麻烦帮忙看一下什么原因吧，感谢

**Comment by Tencent-Alice** [comment]
您好 根据您的问题 有复现的视频吗  可以复现看下 
技术问题 欢迎交流 Q2562367495 注明来意
