### ISSUE TITLE
vue2版本的音视频通话

### ISSUE THREAD

**Issue by andyzhang0511** [Tencent-RTC/TUICallKit#165]
你好，有vue2版本的音视频通话SDK吗？目前在官方上看到的是vue3+ts，vite构建的。

我这边的需求是：
第一步：PC web端发起音视频通话
第二步：在h5端收到PC端发来的通话，随后就开始音视频通话。
但是 ,h5是以webView的形式内嵌入到app端的。PC端和h5端都是vue2写的。
请教下这种场景，腾讯的TRTC是否能支持？

**Comment by Tencent-Alice** [comment]
您好 目前准备接入含UI的方案 web端的吗 可以参考  https://cloud.tencent.com/document/product/647/74765 
技术问题 欢迎交流 Q2562367495 注明来意

**Comment by Tencent-Alice** [comment]
webview的方式可以 不过会有些已知问题 您可以参考下
https://web.sdk.qcloud.com/trtc/webrtc/doc/zh-cn/tutorial-02-info-webrtc-issues.html#h2-5

**Comment by wbxl2000** [comment]
您好，其他版本的音视频通话需求辛苦填写一下问卷～

```text
我们团队即将在 Web 端丰富更多不同的组件，以满足您的开发需求。
希望您能抽出几分钟时间，为您自己的需求投上一票，我们将优先开发！
问卷地址：https://wj.qq.com/s2/11263124/1556/
```

**Comment by wbxl2000** [comment]
现在 Vue2 + TS 已经可以用了，Vue 需要升级到 2.7 以上，CallKit 升级到 1.4.0 以上

**Comment by wbxl2000** [comment]
CallKit Vue2 已经发布~https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2
