### ISSUE TITLE
你好，uniapp小程序vue3demo的代码好像有错误

### ISSUE THREAD

**Issue by Jinl-k** [Tencent-RTC/TUICallKit#175]
![image](https://user-images.githubusercontent.com/39037760/206439173-b388515e-f199-4b11-96c0-c1674b3f9a83.png)
得改成这样
![image](https://user-images.githubusercontent.com/39037760/206439285-ac08d82f-769d-4353-8e43-5d3c8c96acf8.png)
不然点搜索的时候会报错: userIDToSearch not defined.

还有就是，通话过程中没有声音，并且一方挂断了另一方依然在通话中不会挂断。我是下载最新的demo运行的。

**Comment by Jinl-k** [comment]
第二个问题解决了

**Comment by Tencent-Alice** [comment]
HI 根据您的问题 ，可以提供下报错截图吗，以便更好的定位到问题
技术问题 欢迎交流 Q2562367495 注明来意
