### ISSUE TITLE
iOS-1.4.0.255-发起视频通话报-1204

### ISSUE THREAD

**Issue by StillDreamer** [Tencent-RTC/TUICallKit#203]
sdkappid：1400222025
useridA：doctor-py-dev-5e37b9da5f02bf52ba5c6a41-01-app
时间： 2023-03-09 16:37左右
问题描述：在上一次视频通话结束后，发起视频通话报-1204。控制台显示上一次通话的房间没有结束，参与用户只有1人。

**Comment by 1171663207** [comment]
您好，很高兴收到您的反馈，我们会在下一个版本处理这个问题，感谢！感谢！
