### ISSUE TITLE
用uni做的H5引入@tencentcloud/call-uikit-vue2会报错

### ISSUE THREAD

**Issue by linhaobo** [Tencent-RTC/TUICallKit#244]
用uni做的H5引入@tencentcloud/call-uikit-vue2会报错误
TypeError: Object(...) is not a function
    at ./node_modules/@tencentcloud/call-uikit-vue2/dist/tuicall-uikit-vue2.es.js
改怎么解决呢

**Comment by rgzhaoh** [comment]
[@tencentcloud/call-uikit-vue2](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2) supports up to vue2.7. vue2 in uni uses vue2.6, so it won't work. Suggestion: [@tencencit-uikit-vue2]. Suggestion: [@tencentcloud/call-uikit-vue2](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2) should not be used in uniapp. You can use [@tencentcloud/call-uikit-vue2.6](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2.6).

[@tencentcloud/call-uikit-vue2](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2) 最低支持到 vue2.7。而 uni 中的 vue2 用的是 vue2.6。因此无法使用。建议：[@tencentcloud/call-uikit-vue2](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2) 不要在 uniapp 使用。可以使用 [@tencentcloud/call-uikit-vue2.6](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2.6).

**Comment by WhiteCjy** [comment]
> [@tencentcloud/call-uikit-vue2](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2) supports up to vue2.7. vue2 in uni uses vue2.6, so it won't work. Suggestion: [@tencencit-uikit-vue2]. Suggestion: [@tencentcloud/call-uikit-vue2](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2) should not be used in uniapp. You can use [@tencentcloud/call-uikit-vue2.6](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2.6).
> 
> [@tencentcloud/call-uikit-vue2](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2) 最低支持到 vue2.7。而 uni 中的 vue2 用的是 vue2.6。因此无法使用。建议：[@tencentcloud/call-uikit-vue2](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2) 不要在 uniapp 使用。可以使用 [@tencentcloud/call-uikit-vue2.6](https://www.npmjs.com/package/@tencentcloud/call-uikit-vue2.6).

uni-app 使用 @tencentcloud/call-uikit-vue2.6 初始化也报这个错
[TUICallKit] Initialization failed. Reason: TypeError: this._chat.on is not a function
