### ISSUE TITLE
VUE3集成 TUICallKit 配置完成后, 拨打视频出去提示错误码 65535

### ISSUE THREAD

**Issue by ONE-0508** [Tencent-RTC/TUICallKit#259]
根据官方文档进行代码集成, 已检查没有错误配置的情况

以下为配置好的参数
const SDKAppID = 1600000872; 
const userID = "fenghuo"; 
const callUserID = "one";
const SecretKey = 'xxxxxxx' // 官网粘贴

拨打触发的方法
async function call() {
  await TUICallKitServer.call({ 
    userID: callUserID, 
    type: TUICallType.VIDEO_CALL as number
  }).then()
  .catch(err => {
    message.error('拨通失败' + err);
  }); 
} 

此为报错内容
【CallService】call failed, error: {"code":65535,"name":"TUICallEngineError","message_":"TUICallEngine<call>: failed Cannot read properties of undefined (reading 'conversationType')"}

**Comment by rgzhaoh** [comment]
Reason for the problem: The call fails due to a failure to send an invitation signal. For example, the callee is not logged in.
Solution: Update TUICallKit Component.

问题原因：呼叫失败，主要由于发送邀请信令失败导致。例如：被叫者未登录。
解决方案：更新到最新的 TUICallKit 组件。
