### ISSUE TITLE
音视频通话,有时会出现一方已挂断了，而另一方还保持在通话中的情况

### ISSUE THREAD

**Issue by LBruse** [Tencent-RTC/TUICallKit#44]
sdkappid: 1400487238
userid: oB3oz5SOjaKNE37fCdQbxKe0BC_8
userid: oB3oz5ZRnxgMLfNHlbbHOZ1zv-pU
时间： 2022-04-28 19:35左右
问题描述：使用1对1音视频通话时，有时候会出现一方已经结束通话了，而另一方还处于通话中的问题。
![image](https://user-images.githubusercontent.com/25904146/165879229-f6acdbb4-9ace-4cb7-bcf4-58963a721996.png)

而且有时也会出现通话已接起，但是没有显示对方影像的问题。
![image](https://user-images.githubusercontent.com/25904146/165879257-e211dfa7-46b4-4c82-8fcf-6a492ec4206f.png)

这边是使用了一台设备运行Android App，一台设备运行微信小程序，进行互相视频通话做测试，运行的Demo代码版本为9.6.1，有时候视频通话正常，有时候则会出现这种不正常的情况

**Comment by MinTate** [comment]
嗯嗯，这个是我们后台的一个隐藏BUG，修改正在灰度中，预计5/13号之前就灰度完成了，如果您这边类似case比较多，可以在腾讯云实时音视频这边提工单：https://cloud.tencent.com/document/product/647/19906，我们可以帮您先切~
