### ISSUE TITLE
设置为竖屏分辨率不好使呀

### ISSUE THREAD

**Issue by 253192245** [Tencent-RTC/TUICallKit#47]
![image](https://user-images.githubusercontent.com/30893499/167385609-51b03b37-26b9-4ed4-8b08-fe9f46d3176b.png)

**Comment by MinTate** [comment]
这里设置的是编码的分辨率，即远端看到的分辨率，咱们的问题是希望本地看到时竖屏还是远端看到时竖屏呢？
